[project]
name = "dsrp-ml2-proyecto-final"
version = "0.1.0"
description = "Proyecto final ML Engineering II - Predicción de churn en Telco"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "joblib>=1.6.0",
    "jupyter>=1.1.1",
    "lightgbm>=4.7.0",
    "matplotlib>=3.11.1",
    "mlflow>=3.15.2",
    "numpy>=2.5.2",
    "pandas>=2.3.3",
    "python-dotenv>=1.2.3",
    "scikit-learn>=1.9.0",
    "seaborn>=0.13.2",
    "xgboost>=3.4.1",
]
